# 服务器配置
[server]
# 服务器监听的地址
addr = ":8080"
# token加盐
token_salt = "BBGU~_~|_|zysynl"
# 上传的目录
upload_dir = "./upload"

# 数据库配置
[db]
# postgresql连接地址
postgresql = "host=192.168.56.6 user=postgres password=1425 dbname=seven_cow port=5432 sslmode=disable TimeZone=Asia/Shanghai"

[llm]
# 模型类型，支持：https://www.qiniu.com/ai/models
model_type = "nvidia/llama-3.3-nemotron-super-49b-v1.5"
# 模型接口地址
model_uri = "https://openai.qiniu.com/v1"
# llvm api key
llvm_api_key = "sk-3b0df56d192a48de3fee674eb7c491ab86f69609c1c2e94ea1001556b967829f"
